### ISSUE TITLE
level1: data set management tab

### ISSUE THREAD

**Issue by pogyomo** [EL331-Underline/Project#1]

**Comment by 110souhei** [comment]
python 
can use 4 comand
Create  "file.txt" 
Retrieve "file.txt"
Updata  "file_befor.txt" "file_after.txt"
Delet "file.txt"

**Comment by SNozomi** [comment]
https://qiita.com/Soysoy11110000/items/1cc32ce45d0ba01b609e#:~:text=適しています%E3%80%82-,sqlite3はPythonの標準ライブラリであり、SQLiteを,15%20以降が必要です%E3%80%82
