### ISSUE TITLE
Level2 Comparison tab - Q vs K

### ISSUE THREAD

**Issue by SNozomi** [EL331-Underline/Project#7]
Questioned text と Known texts 間の単語の頻度を比較する。
20語単位で表示される[1-20]。そして、次に頻度の高い単語が20単語表示される[21-40]。
システムの中で比較するわけではなく、単語が表示されるだけ
TOP100ぐらいまで表示して欲しい。

![IMG_1521](https://github.com/EL331-Underline/Project/assets/112811762/c5886855-6e57-4acc-8fe8-7db8771b7987)

**Comment by pogyomo** [comment]
@110souhei 実装するうえで、できるだけsearcher.pyの形式に合わせてほしい(メインのクラスの形式とかテストの形式とか)
